*************************************
***DEFINICION PARA AMBIENTE DE RED***
*************************************
SET OPTIMIZE ON 
SET EXCLUSIVE OFF && PERMITE QUE UNA TABLA ABIERTA EN UNA RED SE PUEDA COMPARTIR 
                  && Y MODIFICAR POR CUALQUIER USUARIO DE LA RED
SET MULTILOCKS ON && PARA QUE SE PUEDAN BLOQUEAR MAS DE UN REGISTRO
SET DELETE ON     && PARA QUE LOS REGISTROS MARCADOS NO SE VISUALICEN
SET REFRESH TO 5  && REFRESCAMIENTO CADA 5 SEGUNDOS EN UNA VENTANA EXAMINAR ABIERTA con BROWSE
                  && CHANGE o EDIT
SET REPROCESS TO 5 SECONDS && SI DESPUES DE 5 SEGUNDOS NO PUEDE ACTUALIZARLO FOX MANDA UN ERROR. 
*************************************
SET SYSMENU OFF
SET TALK OFF      && DESACTIVA LA VISUALIZACION DE RESULTADOS DE LOS COMANDOS 
SET CENTURY ON    && 4 DIGITOS PARA EL AÑO
SET DATE DMY      && FORMATO DE FECHA DIA/MES/AÑO
SET ANSI ON       && LA CADENA MAS CORTA SE RELLENARA CON LOS ESPACIOS EN BLANCO NECESARIOS
                  && PARA IGUALAR A LA LONGITUD DE LA CADENA MAS LARGA. ("TOMMY"<>"TOM  ")
SET ESCAPE OFF    && DESACTIVA LA TECLA ESC
SET NEAR ON       && COLOCA EL PUNTERO DE REGISTRO AL FINAL DE LA TABLA, EN CASO DE 
                  && QUE UNA BUSQUEDA DE REGISTRO MEDIANTE FIND O SEEK NO TENGA EXITO. 
SET NOTIFY ON     && CONECTA LA VISUALIZACION DE MENSAJES DEL SISTEMA
SET FDOW TO 2
********************************


_SCREEN.CAPTION="SISTEMA DE INVENTARIO VENTAS Y COBRANZAS - SOCIEDAD QUIMICA MERCANTIL S.A."
_SCREEN.WINDOWSTATE=2
_SCREEN.MINBUTTON=.T.
_SCREEN.MAXBUTTON=.F.
_SCREEN.CLOSABLE=.F.
********************
CLEAR MACROS
CLOSE ALL  
CLEAR ALL

SET PROCEDURE TO FUNCIONES.PRG ADDITIVE 

*********
DO FORM FORMCLAVE.SCX
READ EVENTS && INICIA EL PROCESAMIENTO DE EVENTOS
********************
*LO SIGUIENTE SE EJECUTARA CUANDO SE LLAME A CLEAR EVENTS EN ALGUNA PARTE DEL SISTEMA
********************
CLOSE ALL
CLEAR ALL
*****************************
RELEASE ALL EXTENDED  && LIBERA DE LA MEMORIA TODAS LAS VARIABLES Y MATRICES Y TODAS 
                      && LAS VARIABLES PUBLICAS
                      
SET SYSMENU TO DEFAULT







